### ISSUE TITLE
Temperature Tile

### ISSUE THREAD

**Issue by Wellze** [jpansarasa/SmartThings#2]
Hello

There is no temperature tile on this device, however the unit apparently has a temperature sensor.  Other than that it works fine

**Comment by Wellze** [comment]
Hello again,

I have the STV2 hub and I have installed the Aeon Labs Heavy Duty Smart Energy Switch for my garage heater

The switch works great!  I installed your code for this device and it too works great

When I go to graph smart things and look up that switch I can see its pulling temperature off the unit, however in my smartthings app I don't see temperature.  Is there anyway to show temp in one of the available tiles?

Thanks in advance and thanks for the code!

**Comment by jpansarasa** [comment]
It has been so long since I have looked at this code. On quick inspection I would say _yes?_

If you see it is pulling the temperature in the graph, then it should be possible to map it using a "valueTile" just like you see for "power", "current", and "voltage".

I remember looking at the temps once and they read much different than the other temp sensor I had in my basement. I found the temp sensor and it is on the circuit board which really does not get any airflow, so I don't know how good it will be at reading the ambient temperature in the room.

I don't think you can break much by hacking around the code. You can always replace it with the version here if it stops working.

Good luck

**Comment by jpansarasa** [comment]
yeah, like I suspected:

Currently I see the device reporting
temperature: 82.09 F

I have a SmartSense Multi Device right next to it a few feet away and it reads
temperature: 59 F

I don't think you are going to get what you want from that temp sensor

**Comment by Wellze** [comment]
Hi James,

Thank you so much for answering my inquiry.  I took your advice and picked
up the Multisensor 6 and automated the heater off that.  I love it.  It
works great!

Thanks for the advice man

Kyle Wells, PhD

Bioproducts and Energy
Hinton Pulp
A Division of West Fraser Mills Ltd
cell: 780 817 0866
office: 780 865 8586
